user:
  name:
    max_length: 50
  email:
    max_length: 255
  password:
    min_length: 6
  per_page: 8

users:
  index:
    size: 50
user_helper:
  size: 80
sessions:
  sessions: "1"

micropost:
  max_length: 140
  picture_size: 5
