user:
  name:
    max_length: 50
  email:
    max_length: 255
  password:
    min_length: 6
  per_page: 8
  expire: 2

users:
  index:
    size: 50
    small_size: 30

user_helper:
  size: 80
sessions:
  sessions: "1"

micropost:
  max_length: 140
